name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: Build with dotnet
      run: dotnet build --configuration Release    
    - name: run unit test with dotnet
      run: dotnet test --filter "Category=UNIT-TEST"
    - name: Create single executable file
      run: dotnet publish -r win-x64 -c Release /p:PublishSingleFile=true
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: Publish Directory
        # Directory containing files to upload
        path: Spider-cli\bin\Release\netcoreapp3.1\win-x64\publish
